### ISSUE TITLE
Multiple hyphens causing a 403

### ISSUE THREAD

**Issue by joshmlamb** [seb-jones/dev-server-config#7]
The directory name `gbics-product-catalogue` caused a 403. After renaming the directory to `gbics`, the page loaded correctly.

**Comment by seb-jones** [comment]
@joshmlamb Can't seem to replicate it by creating a `gbics-product-catalogue` directory in `p80` - I  recall that we tweaked `nginx/snippets/home-directory.conf` file on your setup - what are the contents of that file?

**Comment by seb-jones** [comment]
Gonna close this issue since it hasn't cropped up since.
